//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrushWeighProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model2Entities : DbContext
    {
        public Model2Entities()
            : base("name=Model2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SelectAllTicketsByCustomersView> SelectAllTicketsByCustomersViews { get; set; }
        public virtual DbSet<SelectAllTicketsView> SelectAllTicketsViews { get; set; }
        public virtual DbSet<TotalNetWeightByCustomersView> TotalNetWeightByCustomersViews { get; set; }
    }
}
