//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrushWeighProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectAllTicketsView
    {
        public int Id { get; set; }
        public int SeqNumber { get; set; }
        public Nullable<System.DateTime> DateTimeIn { get; set; }
        public Nullable<System.DateTime> DateTimeOut { get; set; }
        public string PlateNumber { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerLocation { get; set; }
        public string CustomerMailAddress { get; set; }
        public string Material { get; set; }
        public string TicketStatus { get; set; }
        public string Driver { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public Nullable<double> GrossWeight { get; set; }
        public Nullable<double> Tare { get; set; }
    }
}
