//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrushWeighProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectAllTicketsByCustomersView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateTimeIn { get; set; }
        public Nullable<System.DateTime> DateTimeOut { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public Nullable<double> GrossWeight { get; set; }
        public Nullable<double> Tare { get; set; }
        public string Status { get; set; }
        public int SeqNumber { get; set; }
    }
}
